// Die drei Haendlerportraets als Pixelbilder, 28 x 32 Punkte.
//
// Jede Zeile ist eine Bildzeile, jedes Zeichen ein Bildpunkt. Welche Farbe
// ein Zeichen bedeutet, steht in `palette`. Der Punkt ist immer der
// Hintergrund.
//
// Warum als Text und nicht als Bilddatei: So bleibt das Spiel ohne fremde
// Dateien, die Bilder sind im Diff lesbar, und eine Farbe laesst sich
// aendern, ohne ein Malprogramm zu oeffnen. Die Bewegung (blinzeln,
// Zunge, Fluegel) liegt in `portraets.js` und wird darueber gezeichnet.

export const PORTRAET_GROMMSCH = { palette:{'.':'#201a15',',':'#2e2318','_':'#3d2c1c','c':'#4a3626','C':'#6d5540','K':'#82684e','k':'#2c2014','s':'#5d7a3a','d':'#42582a','D':'#31421f','h':'#82a054','H':'#a3bd74','e':'#e2cf6a','p':'#17130f','t':'#e0d9bd','n':'#241a12','v':'#3b2d1f','V':'#55402c','m':'#98a0ac','M':'#c7ccd8','g':'#c9a84c'}, zeilen:[
      '............................',
      '..m.........................',
      '..m.................,,......',
      '..m.....cccccccccc..,,,.....',
      '..M....ccCCCCCCCCcc.,,_,....',
      '.......cCCCCKKKCCCc.,,__,...',
      '......ccCCKKKKKKCCcc,,,_,,..',
      '......ckkkkkkkkkkkkc.,,,,...',
      '......dhhhhhhhhhhhhd..,,....',
      '......dhhhHHHHhhhhhd........',
      '......dDDDDhhhDDDDsd........',
      '.ddss.deepshhhspeed..ssdd...',
      '.dsssddssshhhhsssdd..sssd...',
      '..ss..dsshHHHhssd...ss......',
      '......dshHHHHHhsd...........',
      '......dshHpHpHhsd...........',
      '......dsshhhhhhssd..........',
      '......dstnnnnnntsd..........',
      '......ddtssssssttdd.........',
      '.......dsssssssd............',
      '.......ddssssdd.............',
      '.........dssd...............',
      '......vvvvdssdvvvv..........',
      '....vvVVVvvssvvVVVvv........',
      '...vvVVVVvvssvvVVVVvv.......',
      '..vvVVVVVvvggvvVVVVVvv......',
      '..vvVVVVVvvggvvVVVVVvv......',
      '.vvvVVVVVVvvvvvVVVVVVvvv....',
      '.vvvVVVVVVVvvvVVVVVVVvvv....',
      '.vvVVVVVVVVVvvvVVVVVVVVvv...',
      'vvvVVVVVVVVVVvVVVVVVVVVvvv..',
      'vvvvVVVVVVVVVVVVVVVVVVvvvv..'
    ]};

export const PORTRAET_PIPS = { palette:{'.':'#171420',',':'#2c2337','o':'#c65a28','O':'#e07a36','q':'#8f3d1c','y':'#e8b46a','Y':'#f6d492','E':'#fce97a','p':'#1a1210','t':'#e5d9c2','w':'#a34322','W':'#6e2a16','n':'#5c2410','g':'#d9a93c','G':'#f2ce6a','L':'#fff6c8','z':'#a5761f'}, zeilen:[
      '............................',
      '............................',
      '.............,,.............',
      '............,,,,............',
      '.........ooOOOOoo...........',
      '.......ooOOOOOOOOo..........',
      '......toOOOOOOOOOot.........',
      '......oOOOOOOOOOOOo.........',
      '.....ooEEEOOOEEEoo..........',
      '.....ooEpEOOOEpEoo..........',
      '.....ooEEEOOOEEEoo..........',
      '.....oooOOOOOOOooo..........',
      '....ooOOpOOOOOpOOoo.........',
      '....ooOnnnnnnnnnOoo.........',
      'w....ooOOOOOOOOOoo.....w....',
      'ww....oooooooooooo....ww....',
      'Www..ooyyYYYYYYyyoo..wwW....',
      'WWww.ooyYYYYYYYYyoo.wwWW....',
      '.WWwooyYYYYYYYYYYoowwWW.....',
      '..ooqooyYYYYYYYYyooqoo......',
      '..oooooyyYYYYYYyyooooo......',
      '...oooooyyyyyyyyooooo..oo...',
      '....ooooooooooooooo...ooo...',
      '.....ooooooooooooo..oooo....',
      '..gg.zooooooooooozggggg.gg..',
      '.gggGGzzooooooozzGGgggggggg.',
      '.ggGGgggggzzzzzggggGGLgggg..',
      'gggGLGgggggggggggggGGggggggg',
      'ggggGGggggzggggggLggggggzggg',
      'gggggggLgggggggggggggzgggggg',
      'zgggggggggggzgggggggggggggzz',
      'zzzzgggggzzzzzgggggzzzzzzzzz'
    ]};

export const PORTRAET_MALVINA = { palette:{'.':'#181322',',':'#2a1f3d','a':'#241a36','A':'#3b2a58','x':'#54407c','s':'#e0b5a0','S':'#f0d2c0','q':'#c08b74','l':'#b34a5e','m':'#d8dce8','b':'#7488b0','p':'#181020','v':'#3a2a52','V':'#54407c','g':'#d4b258'}, zeilen:[
      '............................',
      '..........aaaaaaa...........',
      '........aaaaaaaaaaa..,......',
      '.......aaaaAAAAaaaaa.,,.....',
      '......aaaAAAAAAAAaaa.,,,....',
      '.....aaaAAxxxxxxAAaaa,,,....',
      '.....aaAAxxxxxxxxAAaa.,,....',
      '....aaaAxxssssssxxAaaa......',
      '....aaAAxsssssssssxAAaa.....',
      '....aaAxsssSSSSsssxxAaa.....',
      '...aaAAxsSSSSSSSSsxAAaa.....',
      '...aaAxsSaaaSSaaaSsxAaa.....',
      '...aaAxmmmmmSmmmmmsxAaa.....',
      '...aaAxmbpmmSmbpmmsxAaa.....',
      '...aaAxsmmmsSSsmmmssxAa.....',
      '...aaAxsSSSSSSSSSSsxxAa.....',
      '....aAxsSSSSqSSSSSsxAaa.....',
      '....aAxsSSSqqqSSSSsxAa......',
      '....aAxssSllllSSssxxAa......',
      '.....AxsssSSSSssssxAaa......',
      '.....Aaxsssssssssxaaa.......',
      '....aAaa.qssssssq.aaaa......',
      '...aaAa..qssssqq..aaaa......',
      '...aaa..ssssssssss..aaa.....',
      '..aaa.sssSSSSSSSSss..aaa....',
      '..aa.vvsSSSSSSSSSsvv..aa....',
      '..aa.vvssSSSgSSSssvv..aa....',
      '..a.vvVssSSgggSSssVvv..a....',
      '....vvVVssSSgSSssVVvv.......',
      '...vvVVVVsssssssVVVVvv......',
      '...vvVVVVVVsssVVVVVVvv......',
      '..vvVVVVVVVVVVVVVVVVVvv.....'
    ]};
